Repository NCUAppTeam/NCU-App, pull requests merged in 2025-05, with the labels that each got.

#159 Enhance Maintainability
  .env.example
  README.md
  src/backend/auth/server.js
  src/components/pages/home/Header.tsx
  src/routes/__root.tsx
  src/routes/callback.tsx
  src/routes/login.tsx
Labels: structure

#161 Refactor
  src/assets/acorn.png
  src/assets/squirrel.jpg
  src/backend/event/Controllers/EventController.ts
  src/backend/user/Controllers/UserController.ts
  src/backend/user/Entities/User.ts
  src/backend/user/Entities/UserFromPortal.ts
  src/backend/user/Entities/UserSignupData.ts
  src/backend/user/Services/UserService.ts
  src/components/pages/auth/isRememberSection.tsx
  src/components/pages/auth/signUpForm.tsx
  src/components/pages/dinner/dinnerlistcard.tsx
  src/components/pages/dinner/dinnerstory.tsx
  src/components/pages/events/eventCard.tsx
  src/components/pages/events/searchBar.tsx
  src/components/pages/home/AcornLoading.tsx
  src/components/pages/home/DrawerOption.tsx
  src/components/pages/home/DrawerSideBar.tsx
  src/components/pages/home/Header.tsx
  src/components/pages/home/LoadingBar.tsx
  src/components/pages/home/SidebarFooter.tsx
  src/components/pages/home/schoolCalendar.tsx
  src/components/pages/home/smallTalk.tsx
  src/components/pages/user/isRememberSection.tsx
  src/main.tsx
  src/routeTree.gen.ts
  src/routes/__root.tsx
  src/routes/calendar/index.tsx
  src/routes/callback.tsx
  src/routes/dinner/index.tsx
  src/routes/events/$eventId.tsx
  src/routes/events/index.tsx
  src/routes/events/select.tsx
  src/routes/home/infoCard.tsx
  src/routes/home/profile.tsx
  src/routes/index.tsx
  src/routes/login.tsx
  src/routes/map/index.tsx
  src/routes/signup.tsx
  src/utils/database.types.ts
  supabase/migrations/20241002170227_remote_schema.sql
  supabase/migrations/20250506074228_remote_schema.sql
  supabase/seed.sql
Labels: enhancement, structure

#162 EventCard Color
  src/backend/event/Entities/Event.ts
  src/backend/event/Services/EventService.ts
  src/backend/user/Controllers/UserController.ts
  src/backend/user/Entities/User.ts
  src/backend/user/Services/UserService.ts
  src/components/pages/events/eventCard.tsx
  src/components/pages/home/DrawerOption.tsx
  src/components/pages/home/DrawerSideBar.tsx
  src/components/pages/home/Header.tsx
  src/components/pages/home/schoolCalendar.tsx
  src/components/pages/home/smallTalk.tsx
  src/routes/events/index.tsx
  src/utils/database.types.ts
  supabase/migrations/20250506090518_remote_schema.sql
Labels: enhancement

#164 Major updates
  src/backend/event/Controllers/EventController.ts
  src/backend/event/Entities/Event.ts
  src/backend/event/Entities/EventInput.ts
  src/backend/event/Entities/EventType.ts
  src/backend/event/Services/EventService.ts
  src/backend/user/Controllers/UserController.ts
  src/backend/user/Entities/User.ts
  src/backend/user/Entities/UserFromPortal.ts
  src/backend/user/Services/UserService.ts
  src/components/pages/events/constants/colorForEvents.ts
  src/components/pages/events/constants/locationForEvents.ts
  src/components/pages/events/constants/textForEvents.ts
  src/components/pages/events/create/FirstStage.tsx
  src/components/pages/events/create/LastStage.tsx
  src/components/pages/events/create/SecondStage.tsx
  src/components/pages/events/create/infoCreate.tsx
  src/components/pages/events/eventCard.tsx
  src/components/pages/events/searchBar.tsx
  src/components/pages/home/AcornLoading.tsx
  src/components/pages/home/DrawerSideBar.tsx
  src/components/pages/home/SidebarFooter.tsx
  src/components/pages/select/belong.tsx
  src/components/pages/select/scale.tsx
  src/components/pages/select/type.tsx
  src/routes/__root.tsx
  src/routes/events/$eventId.tsx
  src/routes/events/create.tsx
  src/routes/events/index.tsx
  src/routes/events/select.tsx
  src/routes/login.tsx
  src/routes/signup.tsx
  src/utils/database.types.ts
  supabase/migrations/20250513104603_remote_schema.sql
  supabase/migrations/20250513105551_remote_schema.sql
  supabase/seed.sql
Labels: structure

#165 Feat: 上傳profile, 修改profile, 載入profile
  src/backend/global/globalFunction.ts
  src/routes/home/profile.tsx
Labels: enhancement
