Repository NCUAppTeam/NCU-App, pull requests merged in 2025-04, with the labels that each got.

#139 Refactor sales and simple Oauth login
  .env.exmaple
  package-lock.json
  package.json
  src/routeTree.gen.ts
  src/routes/login.tsx
  src/routes/sales/add_sell.tsx
  src/routes/sales/index.tsx
  src/routes/sign_up.tsx
  src/utils/database.types.ts
  supabase/migrations/20250318033442_remote_schema.sql
  supabase/seed.sql
Labels: enhancement

#144 feat: integrate the data access from oauth to sign up process page
  src/main.tsx
  src/routeTree.gen.ts
  src/routes/callback.tsx
  src/routes/sign.tsx
  src/routes/signup.tsx
Labels: enhancement

#145 Signup Process Redirection Setup
  src/routeTree.gen.ts
  src/routes/signup.tsx
Labels: enhancement

#150 Nelson test
  src/components/pages/select/belong.tsx
  src/components/pages/select/scale.tsx
  src/components/pages/select/type.tsx
  src/routes/events/$eventId.tsx
  src/routes/events/create.tsx
  src/routes/events/index.tsx
  src/routes/events/select.tsx
  src/routes/sales/index.tsx
  src/utils/database.types.ts
Labels: enhancement

#151 Nelson test
  src/components/pages/select/belong.tsx
  src/components/pages/select/scale.tsx
  src/components/pages/select/type.tsx
  src/routes/events/$eventId.tsx
  src/routes/events/create.tsx
  src/routes/events/index.tsx
  src/routes/events/select.tsx
  src/routes/sales/index.tsx
  src/utils/database.types.ts
Labels: bug, enhancement

#154 fix bug
  src/routes/__root.tsx
Labels: invalid
